disabled_rules:
- trailing_whitespace
- force_cast
- force_try
- force_unwrapping
- identifier_name
- line_length
- shorthand_operator
- type_name
- function_parameter_count
- function_body_length
- nesting
- cyclomatic_complexity
- mark

opt_in_rules:
- empty_count
- empty_string

excluded:
- YELLO-iOS/Application
- YELLO-iOS/Global
